<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Faker\Factory;


class AugmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $faker = Factory::create();
        $tierIds = DB::table('tiers')->pluck('id')->toArray();
        
        DB::table('augments')->insert([
            [
                'name' => 'Afk',
                'description' => 'You cannot perform actions for the next 3 rounds. Afterwards, gain 20 gold.',
                'augment_img' => 'afk.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Band of Thieves I',
                'description' => 'Gain 1 Thiefs Gloves.',
                'augment_img' => 'bandofthievesone.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Beggars can be Choosers',
                'description' => 'You have 3 extra augment rerolls for all other augment choices. Gain 7 gold.',
                'augment_img' => 'beggarscanbechoosers.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Blistering Strikes',
                'description' => 'Your units attacks burn their targets for 5% of their maximum Health over 5 seconds and reduce their targets healing received by 33%.',
                'augment_img' => 'blisteringstrikes.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Branching Out',
                'description' => 'Gain a random Emblem and a Reforger now.',
                'augment_img' => 'branchingout.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Buried Treasures I',
                'description' => 'Description for Augment Tier 3 - B',
                'augment_img' => 'buriedtreasuresone.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Called Shot',
                'description' => 'Set your win streak to +4. Gain a random component (2-1 only) and 2 gold.',
                'augment_img' => 'calledshot.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Caretakers Ally',
                'description' => 'When you reach Level 6, gain a 2-star Tier 3 unit ⇒ Each time you level up, gain the same random Tier 3 champion',
                'augment_img' => 'caretakersally.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Combat Bandages I',
                'description' => 'The first time each ally unit falls below 50% health, restore 300-600 health over 2 seconds.',
                'augment_img' => 'combatbandagesone.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Component Buffet',
                'description' => 'Whenever you would get a random component, instead gain a component anvil.',
                'augment_img' => 'componentbuffet.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Exiles I',
                'description' => 'Your units that start combat with no adajacent allies gain a 25% maximum Health shield for 10 seconds.',
                'augment_img' => 'exilesone.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Featherweights I',
                'description' => 'Your 1 and 2 cost units gain 25% movement and Attack Speed.',
                'augment_img' => 'featherweightsone.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Final Resistance',
                'description' => 'Whenever an ally dies, 30% Shred and Sunder the nearest 4 enemies for 6 seconds.',
                'augment_img' => 'finalresistance.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Find Your Center',
                'description' => 'Your champion that starts combat in the center of the board gains 15% damage and 15% max health.',
                'augment_img' => 'findyourcenter.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fine Vintage',
                'description' => 'Completed items left on your bench for 4 rounds transform into Support items.',
                'augment_img' => 'finevintage.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Good for Something I',
                'description' => 'Champions that arent holding items have a 35% to drop 1 gold on death.',
                'augment_img' => 'goodforsomethingone.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Head Start',
                'description' => 'Gain 3 2* 1-cost units. Disable your shop for the next 3 rounds.',
                'augment_img' => 'headstart.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Help is on the Way',
                'description' => 'After 8 player combats, choose 1 of 4 Support items.',
                'augment_img' => 'helpisontheway.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Iron Assets',
                'description' => 'Gain a Component Anvil and 2 Gold.',
                'augment_img' => 'ironassets.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Item Collector I',
                'description' => 'Your units gain 20 Health. Your team gains 5 Health and 1 AD/AP for each craftable, non-duplicate item equipped (up to 10).',
                'augment_img' => 'itemcollectorone.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Item Grab Bag I',
                'description' => 'Gain 1 random completed item.',
                'augment_img' => 'itemgrabbagone.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Item Ladder',
                'description' => 'Planning phase start: gain a random item that lasts for 1 round. Item quality increases based on stage level.',
                'augment_img' => 'itemladder.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Keepers I',
                'description' => 'At the start of combat, your units grant adjacent allies a 160 health shield for 8 seconds.',
                'augment_img' => 'keepersone.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lategame Specialist',
                'description' => 'Gain 33 gold when you reach Level 9. (Can no longer be offered with Level Up! and vice versa).',
                'augment_img' => 'lategamespecialist.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Latent Forge',
                'description' => 'Gain an Ornn Item Anvil after 7 player combats.',
                'augment_img' => 'latentforge.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lunch Money',
                'description' => 'Every 8 damage you deal to enemy tacticians gives you 2 gold.',
                'augment_img' => 'lunchmoney.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mentorship I',
                'description' => 'If an ally starts combat next to a higher-cost ally, they gain 12% Attack Speed and 150 Health.',
                'augment_img' => 'mentorshipone.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Missed Connections',
                'description' => 'Gain a copy of each Tier One champion.',
                'augment_img' => 'missedconnections.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'One, Two, Five!',
                'description' => 'Gain 1 random component, 2 Gold, and 1 random Tier 5 champion(s).',
                'augment_img' => 'onetwofive.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'One, Twos, Three',
                'description' => 'Gain 2 Tier one unit, 1 Tier two units, and 1 Tier three unit.',
                'augment_img' => 'onetwosthree.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Over Encumbered',
                'description' => 'For the next stage, you only get 1 bench slot(s). After, get 3 item components.',
                'augment_img' => 'overencumbered.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pandoras Bench',
                'description' => 'Gain 2 gold. At the start of every round, champions on the 3 rightmost bench slots transform into random champions of the same cost.',
                'augment_img' => 'pandorasbench.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pandoras Items',
                'description' => 'Round start: items on your bench are randomized (except Tacticians Crown and Spatula).',
                'augment_img' => 'pandorasitems.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Partial Ascension',
                'description' => 'After 15 seconds, your units deal 33% more damage.',
                'augment_img' => 'partialascension.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Patience Is a Virtue',
                'description' => 'If you didnt purchase a champion last turn, gain 1 free reroll. Repeats each round.',
                'augment_img' => 'patienceisavirtue.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Placebo',
                'description' => 'Your team gains 1% attack speed. Gain 10 gold.',
                'augment_img' => 'placebo.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Placebo +',
                'description' => 'Your team gains 1% attack speed. Gain 15 gold.',
                'augment_img' => 'placeboplus.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Precise Planning',
                'description' => 'When you win or lose combat by 3 or less units, gain 2 gold at the start of the next round.',
                'augment_img' => 'preciseplanning.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pumping Up I',
                'description' => 'Your units gain 6% Attack Speed. Each round, increase this by 0.5%.',
                'augment_img' => 'pumpingupone.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Recombobulator',
                'description' => 'Champions on your board permanently transform into random champions 1 Tier higher. Gain 2 Magnetic Removers.',
                'augment_img' => 'recombobulator.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Restart Mission',
                'description' => 'Sell all champions on your board and bench. Gain 2 random 2-star 3-costs, 3 2-star 2-costs, and a 2-star 1-cost champion.',
                'augment_img' => 'restartmission.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Risky Moves',
                'description' => 'Your Tactician loses 20 Health, but after 7 Player combats, gain 33 Gold.',
                'augment_img' => 'riskymoves.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rolling for Days I',
                'description' => 'Gain 9 free Shop refreshes. These Shop refreshes carry over between round.',
                'augment_img' => 'rollingfordaysone.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Row Rejuvenation I',
                'description' => 'Gain 8% Omnivamp, increased by 1% for each champion that starts combat in the same row.',
                'augment_img' => 'rowrejuvenationone.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Silver Spoon',
                'description' => 'Gain 10 XP.',
                'augment_img' => 'silverspoon.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Silver Ticket',
                'description' => 'Gain 3 gold. Every 4 Shop refreshes, gain a free refresh.',
                'augment_img' => 'silverticket.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Silver Veil',
                'description' => 'Your team gains 5% Attack Speed and is immune to the first crowd control effect in combat.',
                'augment_img' => 'silverveil.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Spoils of War I',
                'description' => 'When you kill an enemy unit, theres a 25% chance to drop loot.',
                'augment_img' => 'spoilsofwarone.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Stationary Support I',
                'description' => 'Gain a Target Dummy. In 8 player combats, equip the dummy with 1 random Support Item(s), which cannot be removed.',
                'augment_img' => 'stationarysupportone.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Stimpack',
                'description' => 'Gain 4 components after you lose 50 player health.',
                'augment_img' => 'stimpack.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Team Building',
                'description' => 'Gain a Lesser Champion Duplicator. This happens a second time after 8 player combats.',
                'augment_img' => 'teambuilding.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Teaming Up I',
                'description' => 'Gain 1 random component and 2 random Tier 3 Units.',
                'augment_img' => 'teamingupone.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'The Golden Remover',
                'description' => 'Gain a Golden Remover and component item anvil.',
                'augment_img' => 'thegoldenremover.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tiny Titans',
                'description' => 'Your Tactician heals 30 Health, grows larger, and has 130 maximum Health.',
                'augment_img' => 'tinytitans.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tri Force I',
                'description' => 'Your 3-cost champions gain 150 Health, 10 starting Mana, and 10% Attack Speed.',
                'augment_img' => 'triforceone.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Unified Resistance I',
                'description' => 'Combat start: Your units that share a row with at least 2 other units gain 18 Armor and 18 Magic Resist.',
                'augment_img' => 'unifiedresistanceone.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Young and Wild and Free',
                'description' => 'You can always move freely on Carousel rounds. Gain 2 gold.',
                'augment_img' => 'youngandwildandfree.svg',
                'tier' => '1',
                'set_version' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}