<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ChampionItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        DB::table('champion_item')->insert([
            [
                'champion_id' => 1,
                'item_id' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 1,
                'item_id' => 47,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 1,
                'item_id' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 2,
                'item_id' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 2,
                'item_id' => 52,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 2,
                'item_id' => 47,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 3,
                'item_id' => 27,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 3,
                'item_id' => 31,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 3,
                'item_id' => 32,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 4,
                'item_id' => 44,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 4,
                'item_id' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 4,
                'item_id' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 5,
                'item_id' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 5,
                'item_id' => 34,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 5,
                'item_id' => 41,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 6,
                'item_id' => 44,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 6,
                'item_id' => 45,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 6,
                'item_id' => 57,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 7,
                'item_id' => 26,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 7,
                'item_id' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 7,
                'item_id' => 33,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 8,
                'item_id' => 44,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 8,
                'item_id' => 32,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 8,
                'item_id' => 34,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 9,
                'item_id' => 27,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 9,
                'item_id' => 31,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 9,
                'item_id' => 32,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 10,
                'item_id' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 10,
                'item_id' => 35,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 10,
                'item_id' => 34,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 11,
                'item_id' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 11,
                'item_id' => 52,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 11,
                'item_id' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 12,
                'item_id' => 53,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 12,
                'item_id' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 12,
                'item_id' => 17,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 13,
                'item_id' => 17,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 13,
                'item_id' => 23,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 13,
                'item_id' => 53,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 14,
                'item_id' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 14,
                'item_id' => 26,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 14,
                'item_id' => 32,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 15,
                'item_id' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 15,
                'item_id' => 47,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 15,
                'item_id' => 52,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 16,
                'item_id' => 26,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 16,
                'item_id' => 33,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 16,
                'item_id' => 57,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 17,
                'item_id' => 44,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 17,
                'item_id' => 45,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 17,
                'item_id' => 57,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 18,
                'item_id' => 44,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 18,
                'item_id' => 45,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 18,
                'item_id' => 34,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 19,
                'item_id' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 19,
                'item_id' => 33,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 19,
                'item_id' => 44,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 20,
                'item_id' => 55,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 20,
                'item_id' => 23,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 20,
                'item_id' => 53,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 21,
                'item_id' => 44,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 21,
                'item_id' => 45,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 21,
                'item_id' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 22,
                'item_id' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 22,
                'item_id' => 34,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 22,
                'item_id' => 44,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 23,
                'item_id' => 49,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 23,
                'item_id' => 46,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 23,
                'item_id' => 37,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 24,
                'item_id' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 24,
                'item_id' => 35,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 24,
                'item_id' => 32,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 25,
                'item_id' => 26,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 25,
                'item_id' => 33,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 25,
                'item_id' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 26,
                'item_id' => 27,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 26,
                'item_id' => 31,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 26,
                'item_id' => 32,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 27,
                'item_id' => 53,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 27,
                'item_id' => 46,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 27,
                'item_id' => 17,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 28,
                'item_id' => 23,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 28,
                'item_id' => 37,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 28,
                'item_id' => 42,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 29,
                'item_id' => 49,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 29,
                'item_id' => 42,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 29,
                'item_id' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 30,
                'item_id' => 23,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 30,
                'item_id' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 30,
                'item_id' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 31,
                'item_id' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 31,
                'item_id' => 35,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 31,
                'item_id' => 32,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 32,
                'item_id' => 23,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 32,
                'item_id' => 53,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 32,
                'item_id' => 31,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 33,
                'item_id' => 23,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 33,
                'item_id' => 53,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 33,
                'item_id' => 31,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 34,
                'item_id' => 44,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 34,
                'item_id' => 35,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 34,
                'item_id' => 32,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 35,
                'item_id' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 35,
                'item_id' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 35,
                'item_id' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 36,
                'item_id' => 26,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 36,
                'item_id' => 26,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 36,
                'item_id' => 28,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 37,
                'item_id' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 37,
                'item_id' => 31,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 37,
                'item_id' => 23,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 38,
                'item_id' => 162,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 38,
                'item_id' => 26,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 38,
                'item_id' => 26,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 39,
                'item_id' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 39,
                'item_id' => 33,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 39,
                'item_id' => 43,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 40,
                'item_id' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 40,
                'item_id' => 52,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 40,
                'item_id' => 26,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 41,
                'item_id' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 41,
                'item_id' => 53,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 41,
                'item_id' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 42,
                'item_id' => 23,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 42,
                'item_id' => 42,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 42,
                'item_id' => 53,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 43,
                'item_id' => 53,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 43,
                'item_id' => 42,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 43,
                'item_id' => 17,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 44,
                'item_id' => 44,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 44,
                'item_id' => 35,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 44,
                'item_id' => 32,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 45,
                'item_id' => 57,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 45,
                'item_id' => 26,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 45,
                'item_id' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 46,
                'item_id' => 44,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 46,
                'item_id' => 35,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 46,
                'item_id' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 47,
                'item_id' => 26,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 47,
                'item_id' => 43,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 47,
                'item_id' => 33,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 48,
                'item_id' => 23,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 48,
                'item_id' => 31,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 48,
                'item_id' => 42,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 49,
                'item_id' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 49,
                'item_id' => 31,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 49,
                'item_id' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 50,
                'item_id' => 51,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 50,
                'item_id' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 50,
                'item_id' => 49,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 51,
                'item_id' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 51,
                'item_id' => 52,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 51,
                'item_id' => 47,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 52,
                'item_id' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 52,
                'item_id' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 52,
                'item_id' => 31,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 53,
                'item_id' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 53,
                'item_id' => 33,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 53,
                'item_id' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 54,
                'item_id' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 54,
                'item_id' => 52,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 54,
                'item_id' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 55,
                'item_id' => 44,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 55,
                'item_id' => 35,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 55,
                'item_id' => 34,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 56,
                'item_id' => 44,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 56,
                'item_id' => 35,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 56,
                'item_id' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 57,
                'item_id' => 41,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 57,
                'item_id' => 26,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 57,
                'item_id' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 58,
                'item_id' => 26,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 58,
                'item_id' => 39,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 58,
                'item_id' => 142,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 59,
                'item_id' => 44,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 59,
                'item_id' => 45,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 59,
                'item_id' => 32,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 60,
                'item_id' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 60,
                'item_id' => 35,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'champion_id' => 60,
                'item_id' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ],


        ]);
    }
}
