<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        DB::table('items')->insert([
            [
                'name' => 'B.F. Sword',
                'item_bonus' => '+10% Attack Damage',
                'tier' => 'S',
                'object_img' => 'images/items/bf-sword.png',
                'type_object' => 'Basic',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chain Vest',
                'item_bonus' => '+20 Armor',
                'tier' => 'A',
                'object_img' => 'public/images/items/chainvest.png',
                'type_object' => 'Basic',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Giants Belt',
                'item_bonus' => '+150 Health',
                'tier' => 'S',
                'object_img' => '../../public/images/items/giantbelt.png',
                'type_object' => 'Basic',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Needlessly Large Rod',
                'item_bonus' => '+10 Ability Power',
                'tier' => 'S',
                'object_img' => '../../public/images/items/largerod.png',
                'type_object' => 'Basic',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Negatron Cloak',
                'item_bonus' => '+20 Magic Resist',
                'tier' => 'A',
                'object_img' => '../../public/images/items/negatroncloak.png',
                'type_object' => 'Basic',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Recurve Bow',
                'item_bonus' => '+10% Attack Speed',
                'tier' => 'S',
                'object_img' => '../../public/images/items/recurvebow.png',
                'type_object' => 'Basic',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sparring Gloves',
                'item_bonus' => '+20% Crit Chance',
                'tier' => 'B',
                'object_img' => '../../public/images/items/sparringgloves.png',
                'type_object' => 'Basic',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Spatula',
                'item_bonus' => 'It must do something...',
                'tier' => 'S',
                'object_img' => '../../public/images/items/spatula.png',
                'type_object' => 'Basic',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tear of the Goddess',
                'item_bonus' => '+15 Mana',
                'tier' => 'A',
                'object_img' => '../../public/images/items/tearofthegoddess.png',
                'type_object' => 'Basic',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Adaptive Helm',
                'item_bonus' => 'Combat Start: The holder gains bonuses based on their starting position. Front Two Rows: 15 Ability Power and 40 Armor and Magic Resist. Gain 1 Mana when struck by an attack.Back Two Rows: 20 Ability Power and gain 10 Mana every 3 seconds.',
                'tier' => 'B',
                'object_img' => '../../public/images/items/adaptivehelm.png',
                'type_object' => 'Combined',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Archangels Staff',
                'item_bonus' => 'Grant 20 bonus Ability Power. Combat start: Grant 30 Ability Power every 5 seconds.',
                'tier' => 'B',
                'object_img' => '../../public/images/items/arcangelsstaff.png',
                'type_object' => 'Combined',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bloodthirster',
                'item_bonus' => 'Damage heals the holder for 20% of the damage dealt. Once per combat at 40% Health, gain a 25% maximum Health shield that lasts up to 5 seconds.',
                'tier' => 'A',
                'object_img' => '../../public/images/items/bloodthirster.png',
                'type_object' => 'Combined',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Blue Buff',
                'item_bonus' => 'Max mana reduced by 10.When the holder gets a takedown, they deal 8% more damage for 8 seconds.',
                'tier' => 'S',
                'object_img' => '../../public/images/items/bluebuff.png',
                'type_object' => 'Combined',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bramble Vest',
                'item_bonus' => 'Grants 30 Armor. Negates 50% bonus damage from incoming critical strikes. On being hit by an attack, deal 75/100/150★ magic damage to all nearby enemies (once every 2.5 seconds). (Direct damage item).',
                'tier' => 'A',
                'object_img' => '../../public/images/items/bramblevest.png',
                'type_object' => 'Combined',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Crownguard',
                'item_bonus' => 'Combat start: Shields the holder for 30% of their max health for 8 seconds. When the shield breaks or expires, gain 40 Ability Power.',
                'tier' => 'S',
                'object_img' => '../../public/images/items/crownguard.png',
                'type_object' => 'Combined',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Deathblade',
                'item_bonus' => 'Grant 66% bonus Attack Damage.',
                'tier' => 'A',
                'object_img' => '../../public/images/items/deathblade.png',
                'type_object' => 'Combined',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dragons Claw',
                'item_bonus' => 'Grant 65 bonus Magic Resist. Every 2 seconds, regenerate 9% maximum Health.',
                'tier' => 'S',
                'object_img' => '../../public/images/items/dragonsclaw.png',
                'type_object' => 'Combined',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Edge of Night',
                'item_bonus' => 'Unique: Once per combat: At 60% Health, the holder briefly becomes untargetable and sheds negative effects. Then they gain 15% bonus Attack Speed.',
                'tier' => 'S',
                'object_img' => '../../public/images/items/edgeofnight.png',
                'type_object' => 'Combined',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Eldritch Emblem',
                'item_bonus' => 'The holder gains the Eldritch trait.',
                'tier' => 'S',
                'object_img' => '../../public/images/items/eldritchemblem.png',
                'type_object' => 'Combined',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Evenshroud',
                'item_bonus' => 'Grant 25 Armor and Magic Resist for the first 10 seconds of combat. 50% Sunder enemies within 2 hexes.Sunder: reduce Armor by 50%.',
                'tier' => 'B',
                'object_img' => '../../public/images/items/evenshroud.png',
                'type_object' => 'Combined',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Faerie Emblem',
                'item_bonus' => 'The holder gains the Faerie trait.',
                'tier' => 'B',
                'object_img' => '../../public/images/items/faerieemblem.png',
                'type_object' => 'Combined',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Frost Emblem',
                'item_bonus' => 'The holder gains the Frost trait.',
                'tier' => 'A',
                'object_img' => '../../public/images/items/frostemblem.png',
                'type_object' => 'Combined',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gargoyle Stoneplate',
                'item_bonus' => 'Gain 100 bonus HP. Start with 30 Armor & Magic Restistance. Gain +13 Armor and +13 Magic Resist for each enemy targeting the holder.',
                'tier' => 'A',
                'object_img' => '../../public/images/items/gargoylestoneplate.png',
                'type_object' => 'Combined',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Giant Slayer',
                'item_bonus' => 'Grant 15% bonus Attack Damage and 15 bonus Ability Power. Abilities and attacks deal 30% more damage to enemies with more than 1600 maximum Health.',
                'tier' => 'S',
                'object_img' => '../../public/images/items/giantslayer.png',
                'type_object' => 'Combined',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Guardbreaker',
                'item_bonus' => 'Grant 15% bonus Attack Damage and 10 bonus Ability Power. Abilities and attacks deal 30% more damage to shielded enemies.',
                'tier' => 'S',
                'object_img' => '../../public/images/items/guardbreaker.png',
                'type_object' => 'Combined',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Guinsoos Rageblade',
                'item_bonus' => 'Attacks grant +5% bonus Attack Speed. This effect stacks!',
                'tier' => 'S',
                'object_img' => '../../public/images/items/guinsoosrageblade.png',
                'type_object' => 'Combined',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hand of Justice',
                'item_bonus' => 'Grant 2 effects: +15% Attack Damage and 15 Ability Power, Attacks and Abilities heal for 15% of damage dealt. Each round, randomly increase 1 of these effects by 30%.',
                'tier' => 'B',
                'object_img' => '../../public/images/items/handofjustice.png',
                'type_object' => 'Combined',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hextech Gunblade',
                'item_bonus' => 'Grant 20% Omnivamp. Damage heals the lowest percent Health ally for the same amount.',
                'tier' => 'A',
                'object_img' => '../../public/images/items/hextechgunblade.png',
                'type_object' => 'Combined',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Honeymancy Emblem',
                'item_bonus' => 'The holder gains the Honeymancy trait.',
                'tier' => 'S',
                'object_img' => '../../public/images/items/honeymancyemblem.png',
                'type_object' => 'Combined',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Infinity Edge',
                'item_bonus' => 'Unique: Grants 35% bonus Attack Damage and 15% Critical Strike Chance. Damage from an Ability can critically strike.',
                'tier' => 'A',
                'object_img' => '../../public/images/items/infinityedge.png',
                'type_object' => 'Combined',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ionic Sparke',
                'item_bonus' => 'Gain 150 HP. Enemies within 2 hexes have 50% reduced Magic Resist. When they cast an Ability, they are zapped for magic damage equal to 185% of their maximum Mana. (Direct damage item).',
                'tier' => 'A',
                'object_img' => '../../public/images/items/ionicspark.png',
                'type_object' => 'Combined',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Jeweled Gauntlet',
                'item_bonus' => 'Grant 35 bonus Ability Power and 15% Critical Strike Chance. Damage from an Ability can critically strike.',
                'tier' => 'S',
                'object_img' => '../../public/images/items/jeweledgauntlet.png',
                'type_object' => 'Combined',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Last Whisper',
                'item_bonus' => 'Unique: Grant 10% bonus Attack Damage. Dealing physical damage from an attack or Ability reduces the targets Armor by 50% for 5 seconds. This effect does not stack.',
                'tier' => 'S',
                'object_img' => '../../public/images/items/lastwhisper.png',
                'type_object' => 'Combined',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Morellonomicon',
                'item_bonus' => 'Unique: Grant 10 bonus Ability Power and 10% Attack Speed. Magic or true damage from an Ability burns the holders target, dealing 10% of the targets maximum Health as true damage over 10 seconds and reducing healing by 30% for the duration of the burn.',
                'tier' => 'A',
                'object_img' => '../../public/images/items/morellonomicon.png',
                'type_object' => 'Combined',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nashors Tooth',
                'item_bonus' => 'After casting an Ability, gain 40% Attack Speed for 5 seconds.',
                'tier' => 'S',
                'object_img' => '../../public/images/items/nashorstooth.png',
                'type_object' => 'Combined',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Portal Emblem',
                'item_bonus' => 'The holder gains the Portal trait.',
                'tier' => 'A',
                'object_img' => '../../public/images/items/portalemblem.png',
                'type_object' => 'Combined',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Protectors Vow',
                'item_bonus' => 'Grant 45 bonus starting Mana. Once per combat: At 40% Health, gain a 25% maximum Health shield that lasts up to 5 seconds and 20 Armor and 20 Magic Resist for the rest of combat.',
                'tier' => 'A',
                'object_img' => '../../public/images/items/protectorsvow.png',
                'type_object' => 'Combined',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pyro Emblem',
                'item_bonus' => 'The holder gains the Pyro trait.',
                'tier' => 'A',
                'object_img' => '../../public/images/items/pyroemblem.png',
                'type_object' => 'Combined',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Quicksilver',
                'item_bonus' => 'Grants 20% bonus Attack Speed. Combat start: immune to crowd control for 15 seconds.',
                'tier' => 'B',
                'object_img' => '../../public/images/items/quicksilver.png',
                'type_object' => 'Combined',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rabadons Deathcap',
                'item_bonus' => 'Grant 50 bonus Ability Power and 20% bonus Damage.',
                'tier' => 'A',
                'object_img' => '../../public/images/items/rabadonsdeathcap.png',
                'type_object' => 'Combined',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Red buff',
                'item_bonus' => 'Deal 6% bonus damage. Attacks and Abilities 1% Burn and 33% Wound enemies for 5 seconds.Burn: Deals a percent of the targets maximum Health as true damage every second Wound: Reduces healing received',
                'tier' => 'S',
                'object_img' => '../../public/images/items/redbuff.png',
                'type_object' => 'Combined',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Redemption',
                'item_bonus' => 'Heal adjacent allies for 15% of their missing Health every 5 seconds. Affected allies take 10% less multi-target damage for 5 seconds (damage reduction does not stack). Aura Item.',
                'tier' => 'A',
                'object_img' => '../../public/images/items/redemption.png',
                'type_object' => 'Combined',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Runaans Hurricane',
                'item_bonus' => 'Grants 20% bonus Attack Damage. Attacks fire a bolt at a nearby enemy, dealing 55% Attack Damage as physical damage. (Direct damage item).',
                'tier' => 'S',
                'object_img' => '../../public/images/items/runaanshurricane.png',
                'type_object' => 'Combined',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Spear of Shojin',
                'item_bonus' => 'Attacks grant 5 bonus mana.',
                'tier' => 'S',
                'object_img' => '../../public/images/items/spearofshojin.png',
                'type_object' => 'Combined',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Statikk Shiv',
                'item_bonus' => 'Grants 15 bonus Ability Power. Every 3rd attack unleashes chain lightning that bounces to 4 enemies, dealing 35 magic damage and reducing their Magic Resist by 50% for 5 seconds. (Direct damage item).',
                'tier' => 'A',
                'object_img' => '../../public/images/items/statikkshiv.png',
                'type_object' => 'Combined',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Steadfast Heart',
                'item_bonus' => 'Take 8% less damage. While above 50% health, take 15% less damage instead.',
                'tier' => 'S',
                'object_img' => '../../public/images/items/steadfastheart.png',
                'type_object' => 'Combined',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Steraks Gage',
                'item_bonus' => 'Once per combat at 60% Health, increase max health by 25% and gain 35% Attack Damage for the rest of combat.',
                'tier' => 'A',
                'object_img' => '../../public/images/items/steraksgage.png',
                'type_object' => 'Combined',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sugarcraft Emblem',
                'item_bonus' => 'The holder gains the Sugarcraft trait.',
                'tier' => 'A',
                'object_img' => '../../public/images/items/sugarcraftemblem.png',
                'type_object' => 'Combined',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sunfire Cape',
                'item_bonus' => 'Grant 250 bonus Health. Every 2 seconds, an enemy within 2 hexes is burned for 10% of their maximum Health as true damage over 10 seconds, and reducing healing by 30% for the duration.s',
                'tier' => 'A',
                'object_img' => '../../public/images/items/sunfirecape.png',
                'type_object' => 'Combined',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tacticians Crown',
                'item_bonus' => 'The holders team gains 1 maximum team size.',
                'tier' => 'S',
                'object_img' => '../../public/images/items/tacticianscrown.png',
                'type_object' => 'Combined',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Thiefs Gloves',
                'item_bonus' => 'Each round: equip 2 random items. Improves with player level! Consumes 3 item slots.',
                'tier' => 'S',
                'object_img' => '../../public/images/items/thiefsgloves.png',
                'type_object' => 'Combined',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Titans Resolve',
                'item_bonus' => 'Grants 2% Attack Damage and 2 Ability Power when attacking or taking damage, stacking up to 25 times. At full stacks, grant 20 Armor and 20 Magic Resist.',
                'tier' => 'A',
                'object_img' => '../../public/images/items/titansresolve.png',
                'type_object' => 'Combined',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Warmogs Armor',
                'item_bonus' => 'Grants 12% bonus Health.',
                'tier' => 'S',
                'object_img' => '../../public/images/items/warmongsarmor.png',
                'type_object' => 'Combined',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Witchcraft Emblem',
                'item_bonus' => 'The holder gains the Witchcraft trait.',
                'tier' => 'S',
                'object_img' => '../../public/images/items/witchcraftemblem.png',
                'type_object' => 'Combined',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Armor of Eternal Flight',
                'item_bonus' => 'Gain 60% increased healing and shielding. Heal for 25% of the Queens damage dealt.Only Faeries can hold this item. Bench the champion to remove it.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/armorofeternalflight.png',
                'type_object' => 'Faerie',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Eternal Monarchs Crown',
                'item_bonus' => 'After dealing damage 12 times, gain % for the rest of combat. After dealing damage 25 times, gain 20% maximum Health, 30% Omnivamp, and 15% damage amp.Only Faeries can hold this item. Bench the champion to remove it.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/eternalmonarchscrown.png',
                'type_object' => 'Faerie',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Faerie Queens Crown',
                'item_bonus' => 'After dealing damage 12 times, gain % for the rest of combat.Only Faeries can hold this item. Bench the champion to remove it.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/faeriequeenscrown.png',
                'type_object' => 'Faerie',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Queenguards Armor',
                'item_bonus' => 'Gain 30% increased healing and shielding. Heal for 12% of the Queens damage dealt.Only Faeries can hold this item. Bench the champion to remove it.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/queenguardsarmor.png',
                'type_object' => 'Faerie',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Absolution',
                'item_bonus' => 'Heal allies within 2 hexes for 25% of their missing Health every 5 seconds. They take 10% less multi-target damage for 5 seconds (damage reduction does not stack).',
                'tier' => 'N',
                'object_img' => '../../public/images/items/absolution.png',
                'type_object' => 'Radiant',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Blessed Bloodthirster',
                'item_bonus' => 'Grant: 40% Omnivamp and 30 bonus AP.Once per combat: At 40% Health, gain a 40% maximum Health shield that lasts up to 5 seconds.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/blessedbloodthirster.png',
                'type_object' => 'Radiant',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Blue Blessing',
                'item_bonus' => 'Max mana reduce by 10.When the holder gets a takedown, they deal 20% more damage for 12 seconds.Unique - Only One Per Champion',
                'tier' => 'N',
                'object_img' => '../../public/images/items/blueblessing.png',
                'type_object' => 'Radiant',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Brink of Dawn',
                'item_bonus' => 'Once per combat: At 60% Health and again at 30% Helath, briefly become untargetable and shed negative effects. Then, gain 50% bonus Attack Speed. This effect stacks. After triggering, restore 100% of the holder’s missing health.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/brinkofdawn.png',
                'type_object' => 'Radiant',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bulwarks Oath',
                'item_bonus' => 'Once per combat: At 40% Health, gain a 70 Armor and Magic Resist for the rest of combat, and a 50% maximum Health shield that lasts up to 10 seconds.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/bulwarksoath.png',
                'type_object' => 'Radiant',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chalice of Charity',
                'item_bonus' => 'Combat start: Grant 45 Ability Power and 10% Omnivamp to the holder and allies within 1 hex in the same row.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/chaliceofcharity.png',
                'type_object' => 'Radiant',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Covalent Spark',
                'item_bonus' => 'Grant 350 HP. 50% Shred enemies within 3 hexes. When enemies cast an Ability, they are alsol zapped for magic damage equal to 200% of their maximum Mana.Also, regenerate 1% maximum Health per second',
                'tier' => 'N',
                'object_img' => '../../public/images/items/covalentspark.png',
                'type_object' => 'Radiant',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Crest of Cinders',
                'item_bonus' => 'Grant 60% Attack Speed. Deal 10% bonus damage. Attacks and Abilities 2% Burn and 50% Wound enemies for 30 seconds.Burn: Deals a percent of the targets maximum Health as true damage every 5 seconds. Wound: Reduces healing received.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/crestofcinders.png',
                'type_object' => 'Radiant',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Demon Slayer',
                'item_bonus' => 'Abilities and attacks deal 60% more damage to enemies with more than 1600 maximum Health.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/demonslayer.png',
                'type_object' => 'Radiant',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dragons Will',
                'item_bonus' => 'Every 2 seconds, regenerate 18% maximum Health.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/dragonswill.png',
                'type_object' => 'Radiant',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dvarapala Stoneplate',
                'item_bonus' => 'Gain 250 Health. Grant 15 Armor and 15 Magic Resist for each enemy targeting holder.Also, regenerate 1.5% maximum Health each second.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/dvarapalastoneplate.png',
                'type_object' => 'Radiant',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Equinox',
                'item_bonus' => '30% Sunder enemies within 2 hexes. Grant 50 Armor and Magic Resist for the first 15 seconds of combat.Sunder: Reduce Armor',
                'tier' => 'N',
                'object_img' => '../../public/images/items/equinox.png',
                'type_object' => 'Radiant',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Eternal Whisper',
                'item_bonus' => 'Any physical damage dealt the 50% Sunders the target for the rest of combat. This effect does not stack.Unique - only one per champion Sunder: reduce Armor.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/eternalwhisper.png',
                'type_object' => 'Radiant',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fist of Fairness',
                'item_bonus' => 'Grant 2 effects: +60% Attack Damage and +60 Ability Power. 30% Omnivamp.Omnivamp: heal for some of damage dealt.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/firstoffairness.png',
                'type_object' => 'Radiant',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dragons Will',
                'item_bonus' => 'Every 2 seconds, regenerate 18% maximum Health.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/dragonswill.png',
                'type_object' => 'Radiant',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Glamorous Gauntlet',
                'item_bonus' => 'Gain 65 AP. Damage from an Ability can critically strike.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/glamorousgauntlet.png',
                'type_object' => 'Radiant',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Guinsoos Reckoning',
                'item_bonus' => 'Grant 20% starting Attack Speed. Attacks grant +8% bonus Attack Speed. This effect stacks.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/guinsoosreckoning.png',
                'type_object' => 'Radiant',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hextech Lifeblade',
                'item_bonus' => 'The holders damage heal them for 35% of the damage dealt. The holder also heals their lowest health ally for the same amount.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/hextechlifeblade.png',
                'type_object' => 'Radiant',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Jaksho the Protean',
                'item_bonus' => 'Combat Start: The holder gains two effects, regardless of starting position. Front Two Rows: 80 Armor and Magic Resist. Gain 2 Mana when struck by an attack. Back Two Rows: 55 Ability Power. Gain 20 Mana every 3 seconds.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/jakshotheprotean.png',
                'type_object' => 'Radiant',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Legacy of the Colossus',
                'item_bonus' => 'Take 16% less damage. While above 40% Health, take 30% less damage, instead.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/legacyofthecolossus.png',
                'type_object' => 'Radiant',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Locket of Targon Prime',
                'item_bonus' => 'When combat begins, the holder and all allies within 3 hexes in the same row gain a shield that blocks 275/325/375★ damage for 25 seconds.Radiant Bonus: Grants 200 Health for all allies at the start of combat.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/loccketoftargonprime.png',
                'type_object' => 'Radiant',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mistral',
                'item_bonus' => 'Combat start: Summon a whirlwind on the opposite side of the arena that removes the closest enemy from combat for 8 seconds. Your team gains 15% Attack Speed.Ignores crowd control immunity',
                'tier' => 'N',
                'object_img' => '../../public/images/items/mistral.png',
                'type_object' => 'Radiant',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'More More-ellonomicon',
                'item_bonus' => 'Gain 40 Ability Power and 25% Attack Speed. Damage from the holders Ability 2% Burns and 33% Wounds enemies for 30 seconds.Unique - only 1 per champion Burn: Deals a percent of the targets maximum Health as true damage every second Wound: Reduces healing received',
                'tier' => 'N',
                'object_img' => '../../public/images/items/moremoreellonomicon.png',
                'type_object' => 'Radiant',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Quickestsilver',
                'item_bonus' => 'Combat start: Grant immunity to crowd control for 30 seconds. For 14 seconds, gain 9% Attack Speed every 2 seconds.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/quickestsilver.png',
                'type_object' => 'Radiant',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rabadons Ascended Deathcap',
                'item_bonus' => 'Gain 140 Ability Power and 50% bonus damage. Its witnessed - and unleashed - miracles and calamities both.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/rabadonsascendeddeathcap.png',
                'type_object' => 'Radiant',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rascals Gloves',
                'item_bonus' => 'Each round: Equip 2 random Radiant items.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/rascalsgloves.png',
                'type_object' => 'Radiant',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rosethorn Vest',
                'item_bonus' => 'Reduces 70% bonus damage from incoming critical strikes. On being hit by an attack, deal 125/175/225★ magic damage to all nearby enemies (once every 2 seconds).',
                'tier' => 'N',
                'object_img' => '../../public/images/items/rosethornvest.png',
                'type_object' => 'Radiant',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Royal Crownshield',
                'item_bonus' => 'Combat start: Gain a 50% max health shield for 8 seconds. When the shields expires, gain 50 Ability Power.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/royalcrownshield.png',
                'type_object' => 'Radiant',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Runaans Tempest',
                'item_bonus' => 'Attacks fire a bolt at another nearby enemy, dealing 110% Attack Damage as physical damage.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/runaanstempest.png',
                'type_object' => 'Radiant',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Shroud of Reverance',
                'item_bonus' => 'Combat start: Shoot a wider beam that 50% Mana Reaves enemies. Your team gains 25 starting Mana.Unique - only 1 per champion Mana Reave: increase maximum Mana until the next cast.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/shroudofreverance.png',
                'type_object' => 'Radiant',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Spear of Hirana',
                'item_bonus' => 'Attack restore 20 additional Mana. Gain 50 Ability Power.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/spearofhirana.png',
                'type_object' => 'Radiant',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Statikk Favor',
                'item_bonus' => 'Every third attack unleashes chain lightning that bounces to 8 enemies, dealing 80 magic damage and reducing their Magic Resist by 50% for 5 seconds.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/statikkfavor.png',
                'type_object' => 'Radiant',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Steraks Megashield',
                'item_bonus' => 'Once per combat at 75% Health, increase max health by 40% and gain 60% Attack Damage for the rest of combat.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/steraksmegashield.png',
                'type_object' => 'Radiant',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Stride Breaker',
                'item_bonus' => 'After damaging a shielded enemy, Abilities and attacks 50% deal more damage for 3 seconds.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/stridebreaker.png',
                'type_object' => 'Radiant',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sunlight Cape',
                'item_bonus' => 'Gain 300 Health. Every 1.5 seconds, a random enemy within 3 hexes is burned for 60% of their maximum Health as true damage over 30 seconds. Any healing they receive is reduced by 33%.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/sunlightcape.png',
                'type_object' => 'Radiant',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'The Barons Gift',
                'item_bonus' => 'After casting an Ability, gain 55% Attack Speed for 5 seconds.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/thebaronsgift.png',
                'type_object' => 'Radiant',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Titans Vow',
                'item_bonus' => 'Grant 3% Attack Damage 3 Ability Power when attacking or taking damage, stacking up to 25 times.At full stacks, gain 60 Armor and Magic Resist.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/titansvow.png',
                'type_object' => 'Radiant',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Urf-Angels Staff',
                'item_bonus' => 'Combat start: Gain 40 Ability Power every 4 seconds.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/urfangelsstaff.png',
                'type_object' => 'Radiant',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Warmogs Pride',
                'item_bonus' => 'Gain 20% max health. Regenerate 1.5% max Health per second.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/warmogspride.png',
                'type_object' => 'Radiant',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Willbreaker',
                'item_bonus' => 'Grant bonus 30 Attack Damage and bonus Ability Power. After damaging a shielded enemy, Abilities and attacks deal more damage.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/willbreaker.png',
                'type_object' => 'Radiant',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Zenith Edge',
                'item_bonus' => 'Gain 65% Attack Damage. Damage from an Ability can critically strike.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/zenithedge.png',
                'type_object' => 'Radiant',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Arcana Emblem',
                'item_bonus' => 'The holder gains the Arcana trait.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/arcanaemblem.png',
                'type_object' => 'Non-Craftable',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bastion Emblem',
                'item_bonus' => 'The holder gains the Bastion trait.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/bastionemblem.png',
                'type_object' => 'Non-Craftable',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Blaster Emblem',
                'item_bonus' => 'The holder gains the Blaster trait.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/blasteremblem.png',
                'type_object' => 'Non-Craftable',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chrono Emblem',
                'item_bonus' => 'The holder gains the Chrono trait.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/chronoemblem.png',
                'type_object' => 'Non-Craftable',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hunter Emblem',
                'item_bonus' => 'The holder gains the Hunter trait.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/hunteremblem.png',
                'type_object' => 'Non-Craftable',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Incantor Emblem',
                'item_bonus' => 'The holder gains the Incantor trait.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/incantoremblem.png',
                'type_object' => 'Non-Craftable',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mage Emblem',
                'item_bonus' => 'The holder gains the Mage trait.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/mageemblem.png',
                'type_object' => 'Non-Craftable',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Multistriker Emblem',
                'item_bonus' => 'The holder gains the Multistriker trait.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/multistrikeremblem.png',
                'type_object' => 'Non-Craftable',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Presever Emblem',
                'item_bonus' => 'The holder gains the Presever trait.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/preseveremblem.png',
                'type_object' => 'Non-Craftable',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Scholar Emblem',
                'item_bonus' => 'The holder gains the Scholar trait.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/scholaremblem.png',
                'type_object' => 'Non-Craftable',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Shapeshifter Emblem',
                'item_bonus' => 'The holder gains the Shapeshifter trait.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/shapeshifteremblem.png',
                'type_object' => 'Non-Craftable',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vanguard Emblem',
                'item_bonus' => 'The holder gains the Vanguard trait.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/vanguardemblem.png',
                'type_object' => 'Non-Craftable',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Warrior Emblem',
                'item_bonus' => 'The holder gains the Warrior trait.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/warrioremblem.png',
                'type_object' => 'Non-Craftable',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'A Light Snack (Briar)',
                'item_bonus' => 'Use this on a Briar to grant her 150 Health in exchange for 3HP of your tactician player health.It can only be used once per round.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/alightsnackbriar.png',
                'type_object' => 'Consumable',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Champion Duplicator',
                'item_bonus' => 'Use on a champion to create a 1-star copy on your bench.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/championduplicator.png',
                'type_object' => 'Consumable',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lesser Champion Duplicator',
                'item_bonus' => 'Use on a champion of Tier 3 or less to create a 1-star copy on your bench.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/lesserchampionduplicator.png',
                'type_object' => 'Consumable',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Loaded Dice',
                'item_bonus' => 'Use on a champion to reroll a special Shop that contains only champions sharing a Trait with the source champion.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/loadeddice.png',
                'type_object' => 'Consumable',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Magnetic Remover',
                'item_bonus' => 'Use on a champion to unequip all items.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/magneticremover.png',
                'type_object' => 'Consumable',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Reforger',
                'item_bonus' => 'Use on a champion to unequip all items and randomly transform them into different new ones.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/reforger.png',
                'type_object' => 'Consumable',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Target Dummy',
                'item_bonus' => 'Use on a champion to spawn a movable target dummy nearby.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/targetdummy.png',
                'type_object' => 'Consumable',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Accomplices Gloves',
                'item_bonus' => 'Each round: equip 2 random support items. Improves with player level! Consumes 3 item slots.',
                'tier' => 'S',
                'object_img' => '../../public/images/items/accomplicesgloves.png',
                'type_object' => 'Support',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Aegis of the Legion',
                'item_bonus' => 'Combat start: Empower all allies in the columns behind the holder, granting 25% Attack Speed and 15 Armor and Magic Resist for 12 seconds.',
                'tier' => 'S',
                'object_img' => '../../public/images/items/aegisofthelegion.png',
                'type_object' => 'Support',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'A Light Snack (Briar)',
                'item_bonus' => 'Use this on a Briar to grant her 150 Health in exchange for 3HP of your tactician player health.It can only be used once per round.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/alightsnackbriar.png',
                'type_object' => 'Support',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Banshees Veil',
                'item_bonus' => 'Combat Start: Grant the holder and all allies within 1 hexes in the same row 15% Attack Speed and immunity to crowd control for 18 seconds.',
                'tier' => 'S',
                'object_img' => '../../public/images/items/bansheesveil.png',
                'type_object' => 'Support',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chalice of Power',
                'item_bonus' => 'Grant 22 Ability Power and 10 Mana to the holder and allies within 2 hexes in the same row.',
                'tier' => 'B',
                'object_img' => '../../public/images/items/chaliceofpower.png',
                'type_object' => 'Support',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Crest of Cinders',
                'item_bonus' => 'When combat begins, the holder and all allies within 1 hexes in the same row gain the Crest of Cinders. Units with the Crest of Cinders empower their attacks to Burn their target for 7% of their maximum health as true damage and apply 33% Wound.',
                'tier' => 'S',
                'object_img' => '../../public/images/items/crestofcinders.png',
                'type_object' => 'Support',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Knights Vow',
                'item_bonus' => 'Grant 200 Health and 15% Omnivamp to the holder and allies within 1 hex in the same row.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/knightsvow.png',
                'type_object' => 'Support',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Locket of the Iron Solari',
                'item_bonus' => 'The holder and allies within 2 hexes in the same row gain a 250 damage shield and 20 Armor and 20 Magic Resist for 20 seconds.',
                'tier' => 'S',
                'object_img' => '../../public/images/items/locketoftheironsolari.png',
                'type_object' => 'Support',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Moonstone Renewer',
                'item_bonus' => 'Every 4 seconds, grant a 60-360 Shield (based on stage) to the 2 lowest percent health allies for 4 seconds.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/moonstonerenewer.png',
                'type_object' => 'Support',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Needlessly Big Gem',
                'item_bonus' => 'Your team deals 10% bonus damage. Each second the holder is alive, your team deals an additional 1% bonus damage, up to a total of 25%.',
                'tier' => 'A',
                'object_img' => '../../public/images/items/needlesslybiggem.png',
                'type_object' => 'Support',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Obsidian Cleaver',
                'item_bonus' => 'Attacks and Abilities 50% Shred and 50% Sunder enemies for 10 seconds. Grant your team 8% AD and 8 AP. Shred: reduce Magic Resist Sunder: reduce Armor.',
                'tier' => 'A',
                'object_img' => '../../public/images/items/obsidiancleaver.png',
                'type_object' => 'Support',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Randuins Omen',
                'item_bonus' => 'Combat start: Grant 30 Armor and 30 Magic Resistance to the holder and their adjacent allies.',
                'tier' => 'A',
                'object_img' => '../../public/images/items/randuinsomen.png',
                'type_object' => 'Support',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Shroud of Stillness',
                'item_bonus' => 'Combat Start: Shoot a beam that 30% Mana Reaves enemies. Your team gains 60 Health.Mana Reave: increase maximum Mana until the next cast.',
                'tier' => 'S',
                'object_img' => '../../public/images/items/shroudofstillness.png',
                'type_object' => 'Support',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Spite',
                'item_bonus' => 'The holder and all adjacent allies gain 20% Attack Damage and 20 Ability Power.When this unit dies, Stun all enemies within 2-hexes for 2 seconds.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/spite.png',
                'type_object' => 'Support',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'The Eternal Flame',
                'item_bonus' => 'While the holder is alive, all enemies are 33% Wounded, and all allies deal 8% more damage. This effect refreshes every 5 seconds.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/theeternalflame.png',
                'type_object' => 'Support',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Unstable Treasure Chest',
                'item_bonus' => 'When the holder dies, the 3 closest allies gain a temporary completed item.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/unstabletreasurechest.png',
                'type_object' => 'Support',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Virtue of the Martyr',
                'item_bonus' => 'Every 5 seconds, heal your team for 7% of their max Health. When the holder dies, the healing increases to 14% max Health and for 2 additional heals.',
                'tier' => 'S',
                'object_img' => '../../public/images/items/vitueofthemartyr.png',
                'type_object' => 'Support',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Zekes Herald',
                'item_bonus' => 'Grant 30% Attack Speed to the holder and allies within 2 hexes in the same row.',
                'tier' => 'A',
                'object_img' => '../../public/images/items/zekesherald.png',
                'type_object' => 'Support',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Zephyr',
                'item_bonus' => 'Summon a whirlwind on the opposite side of the arena that removes the closest enemy from combat for 5 seconds. Your team gains 8% Attack Speed.',
                'tier' => 'B',
                'object_img' => '../../public/images/items/zephyr.png',
                'type_object' => 'Support',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ZzRot Portal',
                'item_bonus' => 'Summon a large Voidspawn that Taunts nearby enemies.',
                'tier' => 'S',
                'object_img' => '../../public/images/items/zzrotportal.png',
                'type_object' => 'Support',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Anima Visage',
                'item_bonus' => 'Regenerates 2.5% maximum health each second. Gain 450 Health.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/animavisage.png',
                'type_object' => 'Artifact',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Blacksmiths Gloves',
                'item_bonus' => 'Equip 2 random Ornn Artifacts.Consumes 3 item slots.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/blacksmithsgloves.png',
                'type_object' => 'Artifact',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Blighted Jewel',
                'item_bonus' => 'Dealing magic damage reduces the target’s Magic Resist by 4. If their Magic Resist is 0, this grants the holder 5 Mana instead.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/blightedjewel.png',
                'type_object' => 'Artifact',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Corrupt Vampiric Scepter',
                'item_bonus' => 'Attacks deal an additional 50% Attack Damage as physical damage and heal the holder for the damage dealt.The holder cannot cast their ability or gain mana.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/corruptvampiricscepter.png',
                'type_object' => 'Artifact',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cursed Blade',
                'item_bonus' => 'Attacks reduce the targets max Health by 3%. 13 attacks on the same target reduce their star level by 1.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/cursedblade.png',
                'type_object' => 'Artifact',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Deathfire Grasp',
                'item_bonus' => 'The holder fires a blast of energy at their target, marking them and dealing 20% of their maximum health as magic damage.For the next 10 seconds, the holders abilities and attacks deal 35% increased damage to the marked target, and 25% increased damage to other targets.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/deathfiregrasp.png',
                'type_object' => 'Artifact',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Deaths Defiance',
                'item_bonus' => '50% of the damage the holder receives is instead dealt over 4 seconds as non-lethal damage. The holders Attacks and Abilities also heal for 25% of damage dealt.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/deathsdefiance.png',
                'type_object' => 'Artifact',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Eternal Winter',
                'item_bonus' => 'Enemies who damage the holder have their Attack Speed slowed by 20% for 1.5 seconds. After being slowed this way 7 times, the attacker is Stunned instead, but only once every 15 seconds.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/eternalwinter.png',
                'type_object' => 'Artifact',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fishbones',
                'item_bonus' => 'Doubles the holders attack range, and causes each of their attacks to target a random enemy.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/fishbones.png',
                'type_object' => 'Artifact',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Forbidden Idol',
                'item_bonus' => 'Shields have 50% of their value converted to max Health instead.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/forbiddenidol.png',
                'type_object' => 'Artifact',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gamblers Blade',
                'item_bonus' => 'Gain 1% bonus Attack Speed per gold in your bank (up to 80). Each attack has a 6% chance to drop 1 gold.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/gamblersblade.png',
                'type_object' => 'Artifact',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gold Collector',
                'item_bonus' => 'Attacks and Abilities execute enemies below 12% of their maximum Health. Executions have a 40% chance to drop 1 gold .',
                'tier' => 'N',
                'object_img' => '../../public/images/items/goldcollector.png',
                'type_object' => 'Artifact',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Horizon Focus',
                'item_bonus' => 'Stunning an enemy causes lightning to strike them, dealing 20% of their max Health as magic damage.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/horizonfocus.png',
                'type_object' => 'Artifact',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hullcrusher',
                'item_bonus' => 'If this unit has no adjacent allies at combat start, gain an additional 550 Health.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/hullcrusher.png',
                'type_object' => 'Artifact',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Infinity Force',
                'item_bonus' => 'Health +250, Mana +25, Attack Damage +25%, Ability Power +25, Armor +25, Magic Resist +25, Attack Speed +25%.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/infinityforce.png',
                'type_object' => 'Artifact',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Innervating Locket',
                'item_bonus' => 'The holder gains 2% of their total Mana whenever they are hit by an attack. Each cast restores 20% of the holders max Health over 3 seconds.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/innevatinglocket.png',
                'type_object' => 'Artifact',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lich Bane',
                'item_bonus' => 'The holder’s first attack after each ability cast deals 200/270/340/410/480 (scales with stage) bonus magic damage.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/lichbane.png',
                'type_object' => 'Artifact',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lightshield Crest',
                'item_bonus' => 'Every 3 seconds, Shields the lowest percent Health ally for 50% of the holder’s combined Armor and Magic Resist. On death grants this shield to all allies.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/lightshieldcrest.png',
                'type_object' => 'Artifact',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ludens Tempest',
                'item_bonus' => '100% of overkill damage plus 100 is dealt as magic damage to the three enemies nearest the target.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/ludenstempest.png',
                'type_object' => 'Artifact',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Manazane',
                'item_bonus' => 'Once per combat: After casting an Ability, restore 120 mana over 5 seconds.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/manazane.png',
                'type_object' => 'Artifact',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mittens',
                'item_bonus' => 'Shrinks the holder, granting them increased movement speed, 20% damage reduction, and immunity to Chill.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/mittens.png',
                'type_object' => 'Artifact',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Moguls Mail',
                'item_bonus' => 'Grants 1 Armor, 1 Magic Resist, and 7 Health when taking damage, stacking up to 35 times. At full stacks, continue gaining 1 gold every 6 seconds.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/mogulsmail.png',
                'type_object' => 'Artifact',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Prowlers Claw',
                'item_bonus' => 'After killing a target, shed negative effects and dash to the farthest target within 4 hexes. The next two critical attacks deal 60% bonus critical strike damage.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/prowlersclaw.png',
                'type_object' => 'Artifact',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rapid Firecannon',
                'item_bonus' => 'Gain +1 Attack Range, increased by 1 whenever the holder kills an enemy.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/rapidfirecannon.png',
                'type_object' => 'Artifact',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rocket-Propelled Fist',
                'item_bonus' => 'At the start of combat, the wearer Airborne pulls the farthest enemy into melee range, Stun stunning them for 1.5 seconds. Allies within range will prioritize attacking that enemy.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/rocketpropelledfist.png',
                'type_object' => 'Artifact',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Seekers Armguard',
                'item_bonus' => 'Takedowns increase the holder’s Armor, Magic Resist, and Ability Power by 10, increased to 15 if they score the kill.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/seekersarmguard.png',
                'type_object' => 'Artifact',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Silvermere Dawn',
                'item_bonus' => 'Grants immunity to stuns and the holder’s attacks stun the target for 0.8 seconds.The holder’s attack speed is locked at 0.5.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/silvermeredawn.png',
                'type_object' => 'Artifact',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Snipers Focus',
                'item_bonus' => 'The holders attacks and abilities deal 8% increased damage for each hex between them and their target. Gain +1 Attack range.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/snipersfocus.png',
                'type_object' => 'Artifact',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Spectral Cutlass',
                'item_bonus' => 'Teleports the holder to the mirrored hex on the enemy’s side of the board. After 8 seconds, the holder returns to their original location.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/spectralcutlass.png',
                'type_object' => 'Artifact',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Suspicious Trench Coat',
                'item_bonus' => 'Once per combat at 50% Health, the holder splits into three copies of themself each with 33% of their max Health.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/suspicioustrenchcoat.png',
                'type_object' => 'Artifact',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Talisman Of Ascension',
                'item_bonus' => 'After 22 seconds gain 100% max Health and 120% increased damage for the rest of combat.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/talismanofascension.png',
                'type_object' => 'Artifact',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tricksters Glass',
                'item_bonus' => 'Summon a clone with 70% maximum Health and 30% increased maximum Mana. You cannot equip items to the clone.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/trickstersglass.png',
                'type_object' => 'Artifact',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Unending Despair',
                'item_bonus' => 'Whenever a Shield on the holder breaks, 125% of that Shields initial value is dealt to the nearest enemy as magic damage.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/unendingdespair.png',
                'type_object' => 'Artifact',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wits End',
                'item_bonus' => 'Attacks deal 42-100 (scales with stage) bonus magic damage. Heals the holder for 35% of all magic damage dealt.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/witsend.png',
                'type_object' => 'Artifact',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Zhonyas Paradox',
                'item_bonus' => 'At 40% Health, become invulnerable for 3 seconds.',
                'tier' => 'N',
                'object_img' => '../../public/images/items/zhonyasparadox.png',
                'type_object' => 'Artifact',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
