<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RecipeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('recipes')->insert([
            [
                'id' => 1,
                'item_id' => 169,
                'name' => 'Nothing',
                'description' => 'A classic Italian pasta dish made with eggs, cheese, pancetta, and pepper.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'item_id' => 10,
                'name' => 'Adaptive helm',
                'description' => 'A classic Italian pasta dish made with eggs, cheese, pancetta, and pepper.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'item_id' => 11,
                'name' => 'Archangels Staff',
                'description' => 'Creamy pasta dish made with chicken, fettuccine, and Alfredo sauce.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'item_id' => 12,
                'name' => 'Bloodthirster',
                'description' => 'A rich and creamy dish made with beef, mushrooms, onions, and sour cream.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'item_id' => 13,
                'name' => 'Blue buff',
                'description' => 'A colorful and healthy mix of stir-fried vegetables with a savory sauce.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'item_id' => 14,
                'name' => 'Bramble vest',
                'description' => 'A crisp salad with romaine lettuce, croutons, Parmesan cheese, and Caesar dressing.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'item_id' => 15,
                'name' => 'Crownguard',
                'description' => 'A classic Italian pasta dish made with eggs, cheese, pancetta, and pepper.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'item_id' => 16,
                'name' => 'Deathblade',
                'description' => 'A classic Italian pasta dish made with eggs, cheese, pancetta, and pepper.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'item_id' => 17,
                'name' => 'Dragons claw',
                'description' => 'Creamy pasta dish made with chicken, fettuccine, and Alfredo sauce.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'item_id' => 18,
                'name' => 'Edge of night',
                'description' => 'A rich and creamy dish made with beef, mushrooms, onions, and sour cream.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'item_id' => 19,
                'name' => 'Eldritch Emblem',
                'description' => 'A colorful and healthy mix of stir-fried vegetables with a savory sauce.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'item_id' => 20,
                'name' => 'Evenshroud',
                'description' => 'A crisp salad with romaine lettuce, croutons, Parmesan cheese, and Caesar dressing.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'item_id' => 21,
                'name' => 'Faerie Emblem',
                'description' => 'A classic Italian pasta dish made with eggs, cheese, pancetta, and pepper.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'item_id' => 22,
                'name' => 'Frost Emblem',
                'description' => 'A classic Italian pasta dish made with eggs, cheese, pancetta, and pepper.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'item_id' => 23,
                'name' => 'Gargoyle Stoneplate',
                'description' => 'Creamy pasta dish made with chicken, fettuccine, and Alfredo sauce.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'item_id' => 24,
                'name' => 'Giant Slayer',
                'description' => 'A rich and creamy dish made with beef, mushrooms, onions, and sour cream.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'item_id' => 25,
                'name' => 'Guardbreaker',
                'description' => 'A colorful and healthy mix of stir-fried vegetables with a savory sauce.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'item_id' => 26,
                'name' => 'Guinsoos Rageblade',
                'description' => 'A crisp salad with romaine lettuce, croutons, Parmesan cheese, and Caesar dressing.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'item_id' => 27,
                'name' => 'Hand of Justice',
                'description' => 'A classic Italian pasta dish made with eggs, cheese, pancetta, and pepper.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'item_id' => 28,
                'name' => 'Hextech Gunblade',
                'description' => 'A classic Italian pasta dish made with eggs, cheese, pancetta, and pepper.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 21,
                'item_id' => 29,
                'name' => 'Honeymancy Emblem',
                'description' => 'Creamy pasta dish made with chicken, fettuccine, and Alfredo sauce.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 22,
                'item_id' => 30,
                'name' => 'Infinity Edge',
                'description' => 'A rich and creamy dish made with beef, mushrooms, onions, and sour cream.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 23,
                'item_id' => 31,
                'name' => 'Ionic Spark',
                'description' => 'A colorful and healthy mix of stir-fried vegetables with a savory sauce.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 24,
                'item_id' => 32,
                'name' => 'Jeweled Gauntlet',
                'description' => 'A crisp salad with romaine lettuce, croutons, Parmesan cheese, and Caesar dressing.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 25,
                'item_id' => 33,
                'name' => 'Last Whisper',
                'description' => 'A classic Italian pasta dish made with eggs, cheese, pancetta, and pepper.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 26,
                'item_id' => 34,
                'name' => 'Morellonomicon',
                'description' => 'A classic Italian pasta dish made with eggs, cheese, pancetta, and pepper.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 27,
                'item_id' => 35,
                'name' => 'Nashors Tooth',
                'description' => 'Creamy pasta dish made with chicken, fettuccine, and Alfredo sauce.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 28,
                'item_id' => 36,
                'name' => 'Portal Emblem',
                'description' => 'A rich and creamy dish made with beef, mushrooms, onions, and sour cream.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 29,
                'item_id' => 37,
                'name' => 'Protectors Vow',
                'description' => 'A colorful and healthy mix of stir-fried vegetables with a savory sauce.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 30,
                'item_id' => 38,
                'name' => 'Pyro Emblem',
                'description' => 'A crisp salad with romaine lettuce, croutons, Parmesan cheese, and Caesar dressing.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 31,
                'item_id' => 39,
                'name' => 'Quicksilver',
                'description' => 'A classic Italian pasta dish made with eggs, cheese, pancetta, and pepper.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 32,
                'item_id' => 40,
                'name' => 'Rabadons Deathcap',
                'description' => 'A classic Italian pasta dish made with eggs, cheese, pancetta, and pepper.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 33,
                'item_id' => 41,
                'name' => 'Red Buff',
                'description' => 'Creamy pasta dish made with chicken, fettuccine, and Alfredo sauce.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 34,
                'item_id' => 42,
                'name' => 'Redemption',
                'description' => 'A rich and creamy dish made with beef, mushrooms, onions, and sour cream.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 35,
                'item_id' => 43,
                'name' => 'Runaans Hurricane',
                'description' => 'A colorful and healthy mix of stir-fried vegetables with a savory sauce.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 36,
                'item_id' => 44,
                'name' => 'Spear of Shojin',
                'description' => 'A crisp salad with romaine lettuce, croutons, Parmesan cheese, and Caesar dressing.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 37,
                'item_id' => 45,
                'name' => 'Statikk Shiv',
                'description' => 'A classic Italian pasta dish made with eggs, cheese, pancetta, and pepper.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 38,
                'item_id' => 46,
                'name' => 'Steadfast Heart',
                'description' => 'A classic Italian pasta dish made with eggs, cheese, pancetta, and pepper.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 39,
                'item_id' => 47,
                'name' => 'Steraks Gage',
                'description' => 'Creamy pasta dish made with chicken, fettuccine, and Alfredo sauce.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 40,
                'item_id' => 48,
                'name' => 'Sugarcraft Emblem',
                'description' => 'A rich and creamy dish made with beef, mushrooms, onions, and sour cream.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 41,
                'item_id' => 49,
                'name' => 'Sunfire Cape',
                'description' => 'A colorful and healthy mix of stir-fried vegetables with a savory sauce.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 42,
                'item_id' => 50,
                'name' => 'Tacticians Crown',
                'description' => 'A crisp salad with romaine lettuce, croutons, Parmesan cheese, and Caesar dressing.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 43,
                'item_id' => 51,
                'name' => 'Thiefs Gloves',
                'description' => 'A classic Italian pasta dish made with eggs, cheese, pancetta, and pepper.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 44,
                'item_id' => 52,
                'name' => 'Titans Resolve',
                'description' => 'A classic Italian pasta dish made with eggs, cheese, pancetta, and pepper.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 45,
                'item_id' => 53,
                'name' => 'Warmogs Armor',
                'description' => 'Creamy pasta dish made with chicken, fettuccine, and Alfredo sauce.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 46,
                'item_id' => 54,
                'name' => 'Witchcraft Emblem',
                'description' => 'A colorful and healthy mix of stir-fried vegetables with a savory sauce.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
